"""Generate Top 5% alerts with risk score and exposure time ranking."""

from __future__ import annotations

import argparse
import csv
import math
import os
import sqlite3
from pathlib import Path
from typing import Any


def load_exposure_map(path: Path) -> dict[int, float]:
    exposure_map: dict[int, float] = {}
    if not path.exists():
        return exposure_map

    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                exposure_map[int(row["resident_id"])] = float(row["exposure_time"])
            except (KeyError, TypeError, ValueError):
                continue
    return exposure_map


def get_connection(engine: str, db_path: str) -> Any:
    if engine == "sqlite":
        return sqlite3.connect(db_path)

    try:
        import mysql.connector  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "MySQL engine selected but mysql-connector-python is not installed."
        ) from exc

    return mysql.connector.connect(
        host=os.getenv("MYSQL_HOST", "127.0.0.1"),
        port=int(os.getenv("MYSQL_PORT", "3306")),
        user=os.getenv("MYSQL_USER", "root"),
        password=os.getenv("MYSQL_PASSWORD", ""),
        database=os.getenv("MYSQL_DATABASE", "zovid"),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export top 5% high-risk residents to CSV.")
    parser.add_argument("--engine", choices=["sqlite", "mysql"], default="sqlite", help="Database engine")
    parser.add_argument("--db", default="project.db", help="SQLite database path")
    parser.add_argument("--out", default="outputs/alert_top5.csv", help="Output CSV path")
    parser.add_argument(
        "--exposure",
        default="outputs/exposure_time.csv",
        help="Exposure time CSV generated by simulate_spread.py",
    )
    args = parser.parse_args()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    exposure_map = load_exposure_map(Path(args.exposure))

    conn = get_connection(args.engine, args.db)
    if args.engine == "sqlite":
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
    else:
        cur = conn.cursor(dictionary=True)

    cur.execute(
        """
        SELECT resident_id, full_name, city, risk_score, is_positive, policy_level
        FROM resident_features
        """
    )
    rows = cur.fetchall()

    eligible = []
    for row in rows:
        resident_id = int(row["resident_id"])
        exposure_time = exposure_map.get(resident_id)
        if exposure_time is None or math.isinf(exposure_time):
            continue
        eligible.append(
            {
                "resident_id": resident_id,
                "exposure_time": float(exposure_time),
                "risk_score_neg": -float(row["risk_score"]),
                "row": row,
            }
        )

    eligible.sort(key=lambda x: (x["exposure_time"], x["risk_score_neg"], x["resident_id"]))
    top_n = max(1, math.ceil(len(eligible) * 0.05))
    selected = [x["row"] for x in eligible[:top_n]]

    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "resident_id",
                "exposure_time",
                "risk_score",
                "rank",
                "full_name",
                "city",
                "is_positive",
                "policy_level",
                "alert_label",
            ]
        )

        for rank, row in enumerate(selected, start=1):
            resident_id = int(row["resident_id"])
            writer.writerow(
                [
                    resident_id,
                    round(exposure_map[resident_id], 4),
                    row["risk_score"],
                    rank,
                    row["full_name"],
                    row["city"],
                    row["is_positive"],
                    row["policy_level"],
                    "TOP_5_PERCENT_ALERT",
                ]
            )

    conn.close()


if __name__ == "__main__":
    main()
